### ISSUE TITLE
Accessing the Source code for __QuAM

### ISSUE THREAD

**Issue by ParkerThePineapple** [StationQ/Liquid#22]
I am having issues finding the source code for the __QuAm sample. I am not seeing it in the samples folder. Any suggestions?

**Comment by dbwz8** [comment]
It has not been "tidied up" for release. I'll look into what it will take week.

**Comment by dbwz8** [comment]
The source code is now available. See: `UserCode/DaveWecker/QuAM.fsx` and release comments in `UserCode/DaveWecker/ReadMe.md`. We also exposed a few more APIs to make coding problems like this easier. Enjoy ;)

**Comment by ParkerThePineapple** [comment]
Awesome, thanks so much!

________________________________
