### ISSUE TITLE
Access to output of stab.showState function

### ISSUE THREAD

**Issue by flavamonkey** [StationQ/Liquid#28]
Dear LIQUi|> team,

We are using the Stabilizer simulator and would like to be able to access and manipulate the output of the stab.showState function.

Thank you.

Raja Nagarajan and Antoine Vaillant

**Comment by dbwz8** [comment]
I have placed a new example in UserCode/wecker/Tableau.fsx. It requires a new version of Liquid1.dll (which has been uploaded to the repository). This is from the ReadMe.md file:

### <a name="Tableau"></a>Tableau.fsx

We've been told that people would like to access the internal state of the Stabilizer simulator. Tableau is a new property that will return a tuple of n,rs,xs,zs:

* n             : Number of qubits represented
* rs[2*n+1]     : 0=+1 1=+i 2=-1 3=-i
* xs[2*n+1,ints]: X stablizer values
* zs[2*n+1,ints]: Z stablizer values

ints is the number of ints used to represent the bits (`(n >>> 5) + 1`)

`Tableau.fsx` has a complete implementation of `ShowState` and is demonstrated dumping the tableau for Teleport.

Note: I have _not_ added the Tableau API to the docs (for now). This is a very specialized call and (I believe) it isn't of great use to most users.

You can compile and run the sample with: `\Liquid\bin\Liquid.exe /s Tableau.fsx Tableau()`

**Comment by flavamonkey** [comment]
Thank you for doing this quickly, Dave.

Best,

Raja
