### ISSUE TITLE
A error in user manual

### ISSUE THREAD

**Issue by LionSR** [StationQ/Liquid#29]
Dear Liquid team,
I'm trying to implement Stean7 class acorrding to your nice user manual.
At the page of 56 and 58(Example 53 and Example 55),  one line of the code was replaced by 
"Error! Hyperlink reference not valid."

**Comment by dbwz8** [comment]
Sorry about that. It's been fixed in the User's Manual and the end of the new example looks like this:
```fsharp
Gate.Build(nam,fun () ->
                new Gate(
                    Qubits  = qs.Length,
                    Name    = nam,
                    Help    = "Measure/Fix Syndrome",
                    Draw    = sprintf "\\multigate{#%d}{%s}" (qs.Length-1) nam,
                    Op      = WrapOp op
            ))
```
