### ISSUE TITLE
Specific gate set decomposition/compilation question

### ISSUE THREAD

**Issue by pederico** [StationQ/Liquid#31]
The documentation of Circuit.Compile does not mention if an arbitrary function is only translated into a list of specific gates  from a specified set or liquid instructions are mapped to their gates. Does Liquid support the compilation into specific gate sets?

**Comment by dbwz8** [comment]
LIQUi|> itself really has no understanding of gate sets. A `Gate` definition is really just a recipe for converting a function call into a sequence of one or more unitary matrices. This means that you can define your own gate sets (unitary operations on qubits (sorry, no qtrits or qdits at this time)), write functions that use *your* gates and then compile, optimize and run them. 

So in answer to your questions:
- Arbitrary functions get compiled into the gates that the functions call (at the bottom)
- These gates are definable by the user as unitary matrices
- This allows you to define any gate set you'd like that operates on qubits
