### ISSUE TITLE
Question about __QWalk running on Mac

### ISSUE THREAD

**Issue by svenegas** [StationQ/Liquid#43]
Dear All,

I am a Mac user and I want to run some experiments/simulations using __QWalk(). I understand that a BLAS library is needed in order to run __QWalk() and that uploading BLAS on Liquid is only available on Windows.

I have executed the command mono Liquid.exe "__QWalk(x)" where x is a valid parameter and I have certainly obtained some results. For instance, I ran mono Liquid.exe "__QWalk(tree)" and the results I got have been attached to this message (Liquid.log.txt file)
[Liquid.log.txt](https://github.com/StationQ/Liquid/files/762863/Liquid.log.txt)

My question is: I do not know if running __QWalk() without a BLAS libray actually has a negative impact (that is, errors) on the results I get. Would you please be so kind as to share with me anything you know about the accuracy of running __QWalk() without a BLAS library?

Thank you very much in advance!

Salvador E. Venegas-Andraca

**Comment by alan-geller** [comment]
@svenegas BLAS isn't required to run __QWalk. It is only used to compute page rank.

You should see a line in your output with a message something like:
`loadBLAS Failed: Unable to LoadLibrary(libopenblas.dll): 0x........ [A required library was not found]`

This prevents Liquid from performing the page rank calculation, but everything else should work fine.

**Comment by svenegas** [comment]
Thank you very much indeed for your reply, alan-geller. 

I have borrowed a Windows machine, I have downloaded OpenBLAS-v0.2.19-Win64-int32 and have copied libopenblas.dll in c:\Liquid\bin

Now, I get an error message asking for libgcc_s_seh-1.dll and I do not know what to do. I am not acquainted with OPENBLAS installation or usage. Would it be possible to have access to a step-by-step guide to install and run OPENBLAS?

Thank you very much in advace,

Salvador

**Comment by alan-geller** [comment]
@svenegas I'm not familiar with OPENBLAS, myself, but this link might be helpful: https://github.com/xianyi/OpenBLAS/wiki/How-to-use-OpenBLAS-in-Microsoft-Visual-Studio.
Otherwise, you might try searching for OPENBLAS and .NET or OPENBLAS and Windows.

**Comment by svenegas** [comment]
Sorry for the delay in my reply, I have been having fun with BLAS :) 
Thank you very much for your help, I appreciate it.

Best,

Salvador
