### ISSUE TITLE
Generating Circuit Diagram for Shor's Algorithm in Microsoft LIQUi>

### ISSUE THREAD

**Issue by NickSchleif** [StationQ/Liquid#45]
Hi, my name is Nick.

I'm currently working on a research paper with different quantum simulators. One of the simulators that I'm working with is Microsoft LIQUi> to simulate Shor's algorithm for various input values.

**Is there a simple way for LIQUi> to generate a circuit diagram for a specific instance of Shor's algorithm? Like a line of code in the command prompt?** I've watched the video tutorial, but I have a very limited understanding of using Visual Studio and creating scripts and functions in its environment. 

Thanks!

**Comment by dbwz8** [comment]
Actually, there is no way to do that from the kit. However, we have an internal version that dumps all the circuits used in both HTML and LaTeX. I've uploaded the result to UserCode/DaveWecker/Shor_Render.7z

Also, if you're interested in the basis for this implementation of Shor, take a look at: [Circuit for Shor's algorithm using 2n+3 qubits](https://arxiv.org/abs/quant-ph/0205095). This paper also contains the circuits used.

**Comment by NickSchleif** [comment]
Ok, thanks for the prompt response!

LIQUi> is proving to be a wonderful tool so far, and the runtime of Shor's algorithm is matching the published results well. Thanks again!
