### ISSUE TITLE
incorrect BitControl QASM output from AltOutput.fs

### ISSUE THREAD

**Issue by thiennm** [StationQ/Liquid#47]
Hi,

In the AltOutput.fs script, the parser for BitCon gates of Liquid is incorrect. For example, in the Teleport circuit, it outputs  (c-x q1) instead of (c-x q1,q2).
I guess the problem is because the arity of the BitCon gate is still equal to that of the uncontrolled one.
Simply add the int value of pfx to the arity can fix this.

Thanks!

**Comment by dbwz8** [comment]
Just posted your fix. Thanks!!
