### ISSUE TITLE
Hope that Liquid uses lower .NETFramework version for portability

### ISSUE THREAD

**Issue by xpclove** [StationQ/Liquid#48]
Now Liquid uses “.NETFramework,Version=v4.6.1“  which is higher for portability, such as Ubuntu.
Thanks!

**Comment by dbwz8** [comment]
You need to upgrade your runtime library. The simplest thing to do would be:

 `sudo apt-get update && sudo apt-get dist-upgrade`

The changes were actually tested on Ubuntu, so this should work fine. Please re-open this if it continues to be a problem after you update your system. Thanks!
