### ISSUE TITLE
Operation with different kets or the use of more than 24 qubits 

### ISSUE THREAD

**Issue by gbanegas** [StationQ/Liquid#49]
Hi, 
I searched in the previous issues and I haven't seen this issue/doubt. 
I would like to work with some operations(CNOT) involving qubits.
something like: 
let a = Ket(24).Qubits
CNOT[a.[1];result.[16]]
CNOT[a.[8];result.[16]]

but than I am using 24 qubits and I cannot allocate. 

So, the solution is to create all qubits such as: 
let a = Ket(8).Qubits
let b = Ket(8).Qubits
let result = Ket(8).Qubits 
and apply something like : 
CNOT[a.[1];result.[1]]
CNOT[b.[1];result.[1]]
However, Liquid doesn't allow me to work with different "states", i.e., I received the following error:
Inner: EvalOp: Not all qubits from the same state

Do you know how I can manage to do it? Or in the current state isn't possible? 

Thank you in advance.

**Comment by alan-geller** [comment]
@gbanegas As it says in the README, this version of LIQUi|〉 is limited to a maximum of 23 physical qubits. You can create a circuit on 24 qubits and draw the circuit, but you can't run such a circuit.

**Comment by gbanegas** [comment]
@alan-geller :
So, how they implemented this: 
https://eprint.iacr.org/2017/598.pdf
"LIQU i|i> can simulate roughly 32 qubits in 32GB RAM, however, we make use of the fact that
reversible circuits can be simulated efficiently on classical input states for thousands of qubits."

**Comment by alan-geller** [comment]
@gbanegas The authors of that paper work in my group at Microsoft Research, and have access to an unrestricted version of LIQUi|〉. At this time, I'm afraid we are not making the unrestricted version or the source code available for public use.

**Comment by gbanegas** [comment]
@alan-geller Thank you.. Well, I am going to wait for the "full" version.
