### ISSUE TITLE
Looking for help in compiling the Liquid.sln with VS2017 and windows 10

### ISSUE THREAD

**Issue by zhangxin20121923** [StationQ/Liquid#50]
Hi,
When I add a function in Main.fs file and re-compiler the Liquid.sln according to the user's manual, I met four errors as follow :  
1>FSC: Error FS1225: Failed to find the file next to FSharp.Core "C: \ Liquid \ bin \ FSharp.Core.optdata". The file should be in  C:\Liquid\bin\FSharp.Core.optdata.

1>FSC: Error FS0229: There was an error opening the binary file "C: \ Liquid \ bin \ FSharp.Core.dll": Failed to find the file next to FSharp.Core "C: \ Liquid \ bin \ FSharp.Core.optdata".The file should be in C:\Liquid\bin\FSharp.Core.optdata.

1>FSC: Error FS3160: There was a problem reading the assembly "C: \ Liquid \ bin \ FSharp.Core.dll": There was an error opening the binary file "C: \ Liquid \ bin \ FSharp.Core.dll": Failed to find the file next to FSharp.Core "C: \ Liquid \ bin \ FSharp.Core.optdata". The file should be in  C:\Liquid\bin\FSharp.Core.optdata.

1>FSC: Error FS0073: Internal Error: BuildFrameworkTcImports: no successful import of C:\Liquid\bin\FSharp.Core.dll

Is these any necessary steps before compiler the sln file? I want to know how to fix the error.
Waiting for your answers.

Best regards,
Thanks!

**Comment by dbwz8** [comment]
This looks like a bad installation. Please delete your c:\Liquid directory, copy the current zip file from github and then unpack it in c:\liquid. If the problem persists, I would also re-install Visual Studio Community Edition (or whichever version you're using)... at least the F# part of it. Follow the instructions at: http://stationq.github.io/Liquid/getting-started/

**Comment by zhangxin20121923** [comment]
I will have a try, thank you for your help.
Best regards
