### ISSUE TITLE
Blockchain in QC

### ISSUE THREAD

**Issue by AlephC** [StationQ/Liquid#51]
Hi. I want to test DLT in QC. It´s a professional project. May I try Liquid? How to start?

**Comment by dbwz8** [comment]
Follow the instructions at  [the website](http://stationq.github.io/Liquid/). The kit contains a lot of examples. I would also follow along on the [tutorial video](http://research.microsoft.com/apps/video/default.aspx?id=258279) to get started. As far as it being a ``professional project'', as long as your not selling the results (commerical effort), you're welcome to do all the research you want.
