### ISSUE TITLE
Please solve the halting problem :)

### ISSUE THREAD

**Issue by AceHack** [StationQ/Liquid#52]
https://channel9.msdn.com/Blogs/Charles/Byron-Cook-Terminator-Proving-Good-Things-Will-Eventually-Happen
https://channel9.msdn.com/Shows/Going+Deep/Byron-Cook-Inside-Terminator

Please create a terminator like static software verification using Liquid

Terminator was a microsoft research project that could detect if programs would go into an infinate loop up to like 35,000 lines of code for hardward drivers.

Please impliment this same concept in Liquid or whatever microsoft's newest quantium language is for any length code.  This would effectivly solve the unsolvable halting problem.

This should be easy, knock it out in a day or two.  :)

https://en.wikipedia.org/wiki/Halting_problem
https://en.wikipedia.org/wiki/Microsoft_Terminator

**Comment by pushebp0x539** [comment]
The quantum computer/this emulator of one is a turing machine from my understanding and in such there will always be the halting problem.
Not really an issue for this repository.

**Comment by AceHack** [comment]
Terminator also runs on a turing machine but was able to heuristically solve the halting problem for most cases, it's not 100% but very close.  It would be great to extend this idea to solve it for more cases and lines of code using quantum techniques.

**Comment by dbwz8** [comment]
Since Liquid only simulates a quantum computer on a classical one, you'll have to wait for the real thing to have any hope of attempting this. Since it's not applicable to Liquid, I'm going to close the "issue".
