### ISSUE TITLE
Source code of __QLSA

### ISSUE THREAD

**Issue by qzwtb** [StationQ/Liquid#55]
Hello,

I took up Liquid because I want to program the quantum algorithm of solving linear systems of equations. I found the built-in sample __QLSA just do this, but I have no access to the source code, nor do I have access to changing the matrix A and the vector b. Is that possible for StationQ to upload the source code of __QLSA? Even if the source code is not fully developed to the extend that allows users to use it as function taking arguments A and b, it would still help a lot because I can modify it instead of writing the codes from scratch all by myself.

**Comment by dbwz8** [comment]
I'm sorry, but at this time no further source code is being released. The algorithm is a fairly straight-forward implementation of [HHL](http://arxiv.org/abs/0811.3171) as documented in the User's Manual. Also note that there is no "good way" to invert the eigenvalues... so the implementation only works with solutions that are powers of 2 (inversion = reverse the order of the qubits). Doing an efficient and general QLSA is an ongoing area of research (and why this simple instance doesn't take A or b as input.
