### ISSUE TITLE
Limited Number of Qubits

### ISSUE THREAD

**Issue by mtiepelt** [StationQ/Liquid#61]
Hello,

is there any way to enlarge the number of allocated qubits?

I am working on a 8GB memory machine, giving me at most 23 qubits. Even stepping it up to 30 or more qubits with more memory does not really help (as I would probably need 50+ qubits for any useful tests of arithmetic with signed floats).

As long as I am only working on basis states, without any superposition's, leaving me with pretty much only CNOT gates there should not be much simulation overhead. Is there any way to tell Liquid or to turn Liquid into a "non-quantum" circuit simulator?

(Or perhaps, I should to switch to a "normal" circuit simulation. Can anyone recommend one?)

**Comment by dbwz8** [comment]
You can use the stabilizer simulator which is unlimited in the number of qubits. It will only do Clifford group (X,Y,Z,H,S,CNOT and Measure)... but that should be all you need. This will do thousands of qubits. It's fully documented in the help files and users's manual.

**Comment by dbwz8** [comment]
Please re-open if this doesn't answer your question.

**Comment by dbwz8** [comment]
One other suggestion... Liquid is pretty much in retirement at this point. It has been replaced by the [Quantum Development Kit](https://www.microsoft.com/en-us/quantum/development-kit) (QDK) which has a whole language effort (called `Q#`) and is integrated into the rest of the Microsoft software tool chain. You might want to check it out. There are a *LOT* of samples and professional documentation you might like and will keep improving over time.
